In [1]:
import pandas as pd

df1 = pd.DataFrame({'Emp_ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'Emp_ID': [1, 2, 4], 'Salary': [70000, 80000, 90000]})

# Default inner join
merged_inner = pd.merge(df1, df2, on='Emp_ID')

In [2]:
print("=== Result of Default Inner Join (merged_inner) ===")
display(merged_inner)

=== Result of Default Inner Join (merged_inner) ===

   Emp_ID   Name  Salary
0       1  Alice   70000
1       2    Bob   80000

In [3]:
df1 = pd.DataFrame({'id_left': [1, 2], 'Name': ['Alice', 'Bob']})
df2 = pd.DataFrame({'id_right': [1, 2], 'Salary': [70000, 80000]})

merged = pd.merge(df1, df2, left_on='id_left', right_on='id_right')

In [4]:
# Merging using the left DataFrame's index and right DataFrame's 'id_right' column
merged = pd.merge(df1, df2, left_index=True, right_on='id_right')

In [5]:
merged = pd.merge(df1, df2, left_on='id_left', right_on='id_right', suffixes=('_left_df', '_right_df'))

In [6]:
print("=== Result of Final Merge (merged) ===")
display(merged)

=== Result of Final Merge (merged) ===

   id_left   Name  id_right  Salary
0        1  Alice         1   70000
1        2    Bob         2   80000